### PR TITLE
Skype 1.16 alpha and libcanberra

### LINKED ISSUE #8: Error when running app
Hi,

I installed (I hope it's correct? Its not well documented) this app this way, but it fails to run 
```bash
> flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
> flatpak install gnome org.freedesktop.Platform//1.4
> flatpak install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref
> flatpak run com.skype.Client
Gtk-Message: Failed to load module "canberra-gtk-module"
No protocol specified
```
On the host canberra is installed.

### PR DESCRIPTION
**Pull request by snaggen**
Updated skype sha and size. Also added libcanberra, it might fix #8

### CODE REVIEW

**Comment by alexlarsson** [comment]
Your branch keeps diverging from master, so your PR:s have more and more extra commits in them. Can you pull the latest master and base your PR on that instead?

**Comment by snaggen** [comment]
Yes I noticed that to... before I push I tend to do "git fetch upstream" and "git merge upstream/master".... is that the wrong thing to do?
But I'll pull the latest master and see if I can get in to some sane state....

**Comment by sebix** [comment]
> Yes I noticed that to... before I push I tend to do "git fetch upstream" and "git merge upstream/master".... is that the wrong thing to do?
But I'll pull the latest master and see if I can get in to some sane state....

Simply don't work on the master branch, but on separate branches and keep your master in sync with upstream.

**Comment by alexlarsson** [comment]
Use `git pull --rebase` instead before pulling.

**Pull request merged**
